// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBa_7vVbaCFb_lhxs4qaHmpV5mq7IfU3l0',
    appId: '1:563166931943:web:af0a0e28e93b6977e56b42',
    messagingSenderId: '563166931943',
    projectId: 'testcli-c465f',
    authDomain: 'testcli-c465f.firebaseapp.com',
    storageBucket: 'testcli-c465f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAB17UROfEUwv8Fl6SJ8cWpgQn8b857d8c',
    appId: '1:563166931943:android:42aae8adea603b12e56b42',
    messagingSenderId: '563166931943',
    projectId: 'testcli-c465f',
    storageBucket: 'testcli-c465f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDW0237NnuDDm_vdl8pA_zzbKqcH6I9SMg',
    appId: '1:563166931943:ios:7aac27541ae667fce56b42',
    messagingSenderId: '563166931943',
    projectId: 'testcli-c465f',
    storageBucket: 'testcli-c465f.appspot.com',
    iosBundleId: 'com.example.testcli',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDW0237NnuDDm_vdl8pA_zzbKqcH6I9SMg',
    appId: '1:563166931943:ios:6d7c9a87b1e96bb4e56b42',
    messagingSenderId: '563166931943',
    projectId: 'testcli-c465f',
    storageBucket: 'testcli-c465f.appspot.com',
    iosBundleId: 'com.example.testcli.RunnerTests',
  );
}
